server:
  port: 8090 #程序启动端口

spring:
  application:
    name: rkmonitor
  mail:
    host: smtp.126.com #发送邮件服务器
    username: ruankaomonitor@126.com #发送邮件的邮箱地址
    password: XXXXXXXXXXXXXXXX #客户端授权码，不是邮箱密码，网易的是自己设置的
    properties.mail.smtp.port: 465 #465或者994
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

logging:
  level:
    com.gargoylesoftware.htmlunit: error

to:
  mails: 123@qq.com, 456@qq.com #可以设置多组邮箱，用英文逗号分隔

schedule: 0 */10 * * * ? #每隔10分钟检查一次

